import mongoose from "mongoose"
import dotenv from "dotenv"
import path from "path"

dotenv.config({ path: path.resolve(__dirname, "../../.env") })

import { Category } from "../models/Category"
import { Product } from "../models/Product"
import { Banner } from "../models/Banner"

function createBulkPricing(basePrice: number) {
  return [
    {
      title: "Buy 1 Piece",
      subtitle: "Individual Gift",
      minQty: 1,
      maxQty: 1,
      discountPercent: 0,
      unitPrice: basePrice,
      badgeText: "Single Unit",
      isMostPopular: true,
    },
    {
      title: "Buy 2 - 20 Pieces",
      subtitle: "Small Team & Family",
      minQty: 2,
      maxQty: 20,
      discountPercent: 12,
      unitPrice: Math.round(basePrice * 0.88),
      badgeText: "Save 12%",
      isMostPopular: false,
    },
    {
      title: "More than 20 Pieces",
      subtitle: "Bulk Corporate Order",
      minQty: 21,
      maxQty: 1000,
      discountPercent: 22,
      unitPrice: Math.round(basePrice * 0.78),
      badgeText: "Save 22%",
      isMostPopular: false,
    },
  ]
}

async function seedPsGift() {
  const mongoUri = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/printed_soul_gift"
  console.log(`Connecting to MongoDB at ${mongoUri}...`)
  await mongoose.connect(mongoUri)
  console.log("Connected successfully.")

  // 1. Sync Categories with real images from PS gift/Categories
  const categoriesDefinition = [
    {
      name: "Personalized Gifts",
      slug: "personalized-gifts",
      description: "Custom engraved and printed gifts crafted uniquely for your loved ones",
      image: "/uploads/categories/personalized.webp",
      showOnNavbar: true,
      navDisplayName: "Personalized Gifts",
      showOnHome: true,
      homeOrder: 1,
      sortOrder: 1,
    },
    {
      name: "Diwali & Festive Gifts",
      slug: "diwali-gifts",
      description: "Traditional and modern festive gift hampers with diyas, sweets and dry fruits",
      image: "/uploads/categories/diwali.webp",
      showOnNavbar: true,
      navDisplayName: "Diwali Gifts",
      showOnHome: true,
      homeOrder: 2,
      sortOrder: 2,
    },
    {
      name: "Birthday Gifts",
      slug: "birthday-gifts",
      description: "Make birthdays extra special with personalized keepsakes, lamps and combos",
      image: "/uploads/categories/birthday.webp",
      showOnNavbar: true,
      navDisplayName: "Birthday Gifts",
      showOnHome: true,
      homeOrder: 3,
      sortOrder: 3,
    },
    {
      name: "Gift Hampers",
      slug: "gift-hampers",
      description: "Luxurious curated hampers featuring gourmet treats, gadgets and aromas",
      image: "/uploads/categories/gifts-for-her.webp",
      showOnNavbar: true,
      navDisplayName: "Gift Hampers",
      showOnHome: true,
      homeOrder: 4,
      sortOrder: 4,
    },
    {
      name: "Eco-Friendly Gifts",
      slug: "eco-friendly-gifts",
      description: "Sustainable bamboo notebooks, planters, organic treats and earth-friendly picks",
      image: "/uploads/categories/eco-friendly.webp",
      showOnNavbar: true,
      navDisplayName: "Eco-Friendly Gifts",
      showOnHome: true,
      homeOrder: 5,
      sortOrder: 5,
    },
    {
      name: "Bulk Corporate Gifts",
      slug: "corporate-gifts",
      description: "Premium employee joining kits, executive hampers, brand merchandise & giveaways",
      image: "/uploads/categories/corporate.webp",
      showOnNavbar: true,
      navDisplayName: "Corporate Gifts",
      showOnHome: true,
      homeOrder: 6,
      sortOrder: 6,
    },
    {
      name: "Employee Welcome Kits",
      slug: "employee-welcome-kits",
      description: "First-day joining kits that make newly hired team members feel celebrated",
      image: "/uploads/categories/employee-welcome.avif",
      showOnNavbar: false,
      navDisplayName: "Welcome Kits",
      showOnHome: true,
      homeOrder: 7,
      sortOrder: 7,
    },
    {
      name: "Gifts For Her",
      slug: "gifts-for-her",
      description: "Thoughtfully curated feminine gift hampers, beauty treats & keepsakes",
      image: "/uploads/categories/gifts-for-her.webp",
      showOnNavbar: false,
      navDisplayName: "For Her",
      showOnHome: true,
      homeOrder: 8,
      sortOrder: 8,
    },
    {
      name: "Gifts For Him",
      slug: "gifts-for-him",
      description: "Gentleman executive sets, leather goods, travel mugs and grooming boxes",
      image: "/uploads/categories/gifts-for-him.webp",
      showOnNavbar: false,
      navDisplayName: "For Him",
      showOnHome: true,
      homeOrder: 9,
      sortOrder: 9,
    },
  ]

  const catMap = new Map<string, mongoose.Types.ObjectId>()
  for (const catDef of categoriesDefinition) {
    let cat = await Category.findOne({ slug: catDef.slug })
    if (!cat) {
      cat = await Category.create(catDef)
    } else {
      cat.image = catDef.image
      cat.description = catDef.description
      cat.showOnNavbar = catDef.showOnNavbar
      cat.navDisplayName = catDef.navDisplayName
      cat.showOnHome = catDef.showOnHome
      cat.homeOrder = catDef.homeOrder
      await cat.save()
    }
    catMap.set(catDef.slug, cat._id as mongoose.Types.ObjectId)
  }
  console.log(`Synced ${catMap.size} categories.`)

  // 2. Sync Banners with real images from PS gift/Banner
  await Banner.deleteMany({})
  await Banner.create([
    {
      title: "Luxury Corporate & Welcome Gift Sets",
      subtitle: "Custom-branded executive backpacks, thermal tumblers & onboarding essentials.",
      tag: "EXECUTIVE 2026 COLLECTION",
      imageUrl: "/uploads/banners/corporate_desktop_banner_-giftana.webp",
      link: "/products?category=corporate-gifts",
      buttonText: "Explore Corporate Hampers",
      type: "hero",
      order: 1,
      isActive: true,
    },
    {
      title: "Celebrate Every Birthday With Love",
      subtitle: "Personalized leather accessories, gourmet hampers & precision name-engraved keepsakes.",
      tag: "CURATED CELEBRATION GIFTS",
      imageUrl: "/uploads/banners/birthday_gifts_desktop_banner_-_giftana.webp",
      link: "/products?category=birthday-gifts",
      buttonText: "Shop Birthday Gifts",
      type: "hero",
      order: 2,
      isActive: true,
    },
  ])
  console.log("Synced 2 hero banners.")

  // 3. Delete all old products as requested
  const deletedCount = await Product.deleteMany({})
  console.log(`Deleted ${deletedCount.deletedCount} old placeholder products.`)

  // Category IDs helper
  const catBirthday = catMap.get("birthday-gifts")!
  const catCorporate = catMap.get("corporate-gifts")!
  const catDiwali = catMap.get("diwali-gifts")!
  const catPersonalized = catMap.get("personalized-gifts")!
  const catHampers = catMap.get("gift-hampers")!
  const catEco = catMap.get("eco-friendly-gifts")!

  // 4. Products definition from 'PS gift'
  const newProducts = [
    // ═════════════════════════════════════════════════════════════════
    // CATEGORY: BIRTHDAY GIFTS
    // ═════════════════════════════════════════════════════════════════
    {
      name: "Cozy Escape Gourmet Birthday Hamper",
      slug: "cozy-escape-gourmet-birthday-hamper",
      description:
        "A delightfully warm and comforting birthday celebration hamper featuring artisanal treats, fragrant candle, roasted gourmet nuts, and a celebratory keepsake card.",
      price: 1499,
      comparePrice: 1999,
      images: ["/uploads/products/birthday/Cozy-Escape-1.webp"],
      category: catBirthday,
      stock: 120,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Birthday", "Celebration", "Housewarming"],
      recipient: ["Her", "Him", "Friend", "Family"],
      tags: ["birthday", "hamper", "gourmet", "celebration", "cozy-escape"],
      ratings: { average: 4.9, count: 68 },
      bulkPricingTiers: createBulkPricing(1499),
      hoverMediaType: "image",
    },
    {
      name: "Luxury Birthday Pamper Hamper For Her",
      slug: "luxury-birthday-pamper-hamper-for-her",
      description:
        "An indulgent birthday gift hamper crafted for her, packed with luxury bath amenities, aromatic diffuser, fine chocolates, and satin accessories in a presentation gift box.",
      price: 1899,
      comparePrice: 2499,
      images: ["/uploads/products/birthday/gift-hamper-for-her.webp"],
      category: catBirthday,
      stock: 95,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Birthday", "Anniversary", "Celebration"],
      recipient: ["Her", "Wife", "Sister", "Friend"],
      tags: ["birthday", "for-her", "luxury-hamper", "spa-kit", "pamper"],
      ratings: { average: 4.95, count: 84 },
      bulkPricingTiers: createBulkPricing(1899),
      hoverMediaType: "image",
    },
    {
      name: "Personalized Velvet Jewellery Storage Box - Emerald Green",
      slug: "personalized-velvet-jewellery-box-emerald-green",
      description:
        "Elegant emerald green velvet travel jewellery organiser with modular compartments for rings, necklaces, and earrings. Free gold-foil name customization.",
      price: 799,
      comparePrice: 1199,
      images: ["/uploads/products/birthday/Jewellery_Storage_Box-green.jpg"],
      category: catBirthday,
      stock: 150,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name for Jewellery Box",
      personalizationZones: [
        {
          id: "zone-jewel-name",
          name: "Top Lid Monogram",
          x: 50,
          y: 52,
          fontSize: 18,
          textColor: "#FCD34D",
          rotation: 0,
          isCurved: false,
          maxChars: 14,
          sampleText: "Aaradhya",
        },
      ],
      giftOccasions: ["Birthday", "Anniversary", "Celebration"],
      recipient: ["Her", "Sister", "Friend", "Wife"],
      tags: ["jewellery-box", "birthday", "for-her", "velvet", "personalized"],
      ratings: { average: 4.88, count: 52 },
      bulkPricingTiers: createBulkPricing(799),
      hoverMediaType: "image",
    },
    {
      name: "Kisses Blue Stainless Steel Temperature Tumbler Gift Set",
      slug: "kisses-blue-temperature-tumbler-gift-set",
      description:
        "Double-wall vacuum insulated smart LED temperature tumbler in deep ocean blue accompanied by Hershey's Kisses chocolates in a chic magnetic gift box.",
      price: 999,
      comparePrice: 1499,
      images: ["/uploads/products/birthday/Kisses_Blue_735_Tumbler_5.webp"],
      category: catBirthday,
      stock: 110,
      isFeatured: true,
      isBestSeller: false,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave on Tumbler",
      personalizationZones: [
        {
          id: "zone-tumbler-name",
          name: "Tumbler Body Engraving",
          x: 50,
          y: 62,
          fontSize: 16,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Vikram S.",
        },
      ],
      giftOccasions: ["Birthday", "Celebration", "Friendship Day"],
      recipient: ["Him", "Her", "Friend", "Colleague"],
      tags: ["tumbler", "temperature-bottle", "birthday", "chocolates", "kisses-blue"],
      ratings: { average: 4.85, count: 43 },
      bulkPricingTiers: createBulkPricing(999),
      hoverMediaType: "image",
    },
    {
      name: "Love & Joy Festive Celebration Birthday Box",
      slug: "love-and-joy-festive-celebration-box",
      description:
        "Vibrant celebration gift box filled with gourmet butter cookies, rich chocolate truffles, birthday party blower, and custom birthday card.",
      price: 1299,
      comparePrice: 1799,
      images: [
        "/uploads/products/birthday/Love-Joy-Festive-Gift-Box.webp",
        "/uploads/products/birthday/Love-Joy-Festive-Gift-Box-angle.webp",
      ],
      category: catBirthday,
      stock: 140,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Birthday", "Celebration"],
      recipient: ["Friend", "Family", "Colleague"],
      tags: ["birthday", "celebration", "sweet-box", "cookies", "love-and-joy"],
      ratings: { average: 4.92, count: 77 },
      bulkPricingTiers: createBulkPricing(1299),
      hoverMediaType: "image",
    },
    {
      name: "Premium Brown Leather Wallet Gift Set for Women",
      slug: "premium-brown-leather-wallet-for-women",
      description:
        "Handcrafted vintage brown vegan leather women's wallet with multi-card slots, zippered coin pouch, and laser monogram engraving option.",
      price: 899,
      comparePrice: 1299,
      images: ["/uploads/products/birthday/Premium-Brown-Leather-Wallet-Gifts-for-Women-2.webp"],
      category: catBirthday,
      stock: 85,
      isFeatured: false,
      isBestSeller: false,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name for Wallet",
      personalizationZones: [
        {
          id: "zone-wallet-name",
          name: "Wallet Corner Monogram",
          x: 68,
          y: 78,
          fontSize: 14,
          textColor: "#FEF3C7",
          rotation: 0,
          isCurved: false,
          maxChars: 12,
          sampleText: "Pooja K.",
        },
      ],
      giftOccasions: ["Birthday", "Anniversary", "Mother's Day"],
      recipient: ["Her", "Wife", "Mother", "Sister"],
      tags: ["wallet", "leather", "for-her", "birthday", "personalized"],
      ratings: { average: 4.79, count: 39 },
      bulkPricingTiers: createBulkPricing(899),
      hoverMediaType: "image",
    },
    {
      name: "The Coffee Companion Birthday Hamper",
      slug: "the-coffee-companion-birthday-hamper",
      description:
        "Handpicked gift box for true coffee lovers including artisan ground roast coffee, matte ceramic coffee mug, coffee frother, and biscoff cookies.",
      price: 1599,
      comparePrice: 2199,
      images: ["/uploads/products/birthday/The-Coffee-Companion-1.webp"],
      category: catBirthday,
      stock: 75,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Birthday", "Celebration"],
      recipient: ["Him", "Her", "Friend", "Colleague"],
      tags: ["coffee", "hamper", "birthday", "mug", "coffee-lover"],
      ratings: { average: 4.93, count: 91 },
      bulkPricingTiers: createBulkPricing(1599),
      hoverMediaType: "image",
    },
    {
      name: "4-in-1 Executive Leatherette Combo - Wallet, Pen, Keychain & Cardholder",
      slug: "4-in-1-executive-leatherette-combo-brown",
      description:
        "Timeless 4-in-1 executive birthday gift combo featuring a bi-fold wallet, metal rollerball pen, loop keychain, and visiting cardholder in a gift case.",
      price: 1199,
      comparePrice: 1699,
      images: ["/uploads/products/birthday/wallet-pen-keychain-card-holder_brown_-min.webp"],
      category: catBirthday,
      stock: 130,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave on Combo",
      personalizationZones: [
        {
          id: "zone-combo-wallet",
          name: "Wallet Engraving",
          x: 48,
          y: 45,
          fontSize: 14,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 14,
          sampleText: "Rahul Verma",
        },
      ],
      giftOccasions: ["Birthday", "Farewell", "Anniversary", "Father's Day"],
      recipient: ["Him", "Husband", "Brother", "Father", "Colleague"],
      tags: ["combo-set", "wallet", "pen", "keychain", "birthday", "for-him", "personalized"],
      ratings: { average: 4.91, count: 104 },
      bulkPricingTiers: createBulkPricing(1199),
      hoverMediaType: "image",
    },

    // ═════════════════════════════════════════════════════════════════
    // CATEGORY: CORPORATE GIFTS
    // ═════════════════════════════════════════════════════════════════
    {
      name: "7-in-1 Tech Executive Backpack Welcome Set",
      slug: "7-in-1-tech-executive-backpack-welcome-set",
      description:
        "Premium 7-in-1 corporate kit featuring water-resistant laptop backpack, faux-leather diary, metal pen, metal keychain, foldable mobile stand, vacuum bottle & tumbler.",
      price: 2499,
      comparePrice: 3499,
      images: [
        "/uploads/products/corporate/7-in-1-Bagpack-with-Personalized-Diary-Pen-Keychain-Mobile-Stand-055-Bottle-734-Tumbler-Set-Black_1.webp",
      ],
      category: catCorporate,
      stock: 200,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Company / Employee Name",
      personalizationZones: [
        {
          id: "zone-corp-7in1-diary",
          name: "Diary Cover Engraving",
          x: 52,
          y: 42,
          fontSize: 16,
          textColor: "#FCD34D",
          rotation: 0,
          isCurved: false,
          maxChars: 18,
          sampleText: "Devora Tech",
        },
      ],
      giftOccasions: ["Corporate", "Onboarding", "Annual Event"],
      recipient: ["Employee", "Client", "Executive"],
      tags: ["corporate", "backpack", "welcome-kit", "7-in-1", "tumbler", "personalized"],
      ratings: { average: 4.96, count: 142 },
      bulkPricingTiers: createBulkPricing(2499),
      hoverMediaType: "image",
    },
    {
      name: "Black 8-in-1 Executive Corporate Laptop Bag Onboarding Kit",
      slug: "black-8-in-1-executive-laptop-bag-onboarding-kit",
      description:
        "The ultimate 8-in-1 corporate welcome hamper with padded laptop shoulder bag, branded cotton t-shirt, thermal coffee tumbler, planner diary, metallic pen, keychain, cardholder & mobile stand.",
      price: 2999,
      comparePrice: 4199,
      images: [
        "/uploads/products/corporate/Black-8-in-1-Laptop-Bag-with-Personalized-Diary-and-Pen_-Keychain_-Card-Holder_-Mobile-Stand_-Coffee-Tumbler-350ml-Tshirt.webp",
      ],
      category: catCorporate,
      stock: 180,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Company / Employee Name",
      personalizationZones: [
        {
          id: "zone-corp-8in1-bag",
          name: "Diary Personalization",
          x: 48,
          y: 55,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Ananya Sharma",
        },
      ],
      giftOccasions: ["Corporate", "Onboarding", "Annual Day"],
      recipient: ["Employee", "Client"],
      tags: ["corporate", "8-in-1", "laptop-bag", "welcome-kit", "tshirt", "personalized"],
      ratings: { average: 4.98, count: 187 },
      bulkPricingTiers: createBulkPricing(2999),
      hoverMediaType: "image",
    },
    {
      name: "Black Personalized 6-in-1 Executive Laptop Bag Gift Set",
      slug: "black-personalized-6-in-1-executive-laptop-bag-gift-set",
      description:
        "Sleek and functional 6-in-1 corporate gift set containing premium laptop carry bag, hardcover notebook, roller pen, metal keychain, mobile holder & cardholder.",
      price: 2199,
      comparePrice: 2999,
      images: [
        "/uploads/products/corporate/Black-Personalised-6-in-1-Executive-Laptop-Bag-Gift-Set_1.webp",
      ],
      category: catCorporate,
      stock: 160,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name / Company Logo",
      personalizationZones: [
        {
          id: "zone-corp-6in1-diary",
          name: "Notebook Engraving",
          x: 52,
          y: 48,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Karan Johar",
        },
      ],
      giftOccasions: ["Corporate", "Annual Event", "Client Gifting"],
      recipient: ["Employee", "Client"],
      tags: ["corporate", "laptop-bag", "6-in-1", "executive-kit", "personalized"],
      ratings: { average: 4.89, count: 72 },
      bulkPricingTiers: createBulkPricing(2199),
      hoverMediaType: "image",
    },
    {
      name: "Black Premium Laptop Bag & Office Essentials Gift Set",
      slug: "black-premium-laptop-bag-office-essentials-set",
      description:
        "High-durability office essential gift box with padded laptop sleeve, engraved ballpoint pen, diary organizer, and keychain.",
      price: 1999,
      comparePrice: 2799,
      images: [
        "/uploads/products/corporate/Black-Premium-Personalized-Laptop-Bag-_-Office-Essentials-Gift-Set_1.jpg",
      ],
      category: catCorporate,
      stock: 140,
      isFeatured: false,
      isBestSeller: false,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-corp-essentials-pen",
          name: "Cover Engraving",
          x: 50,
          y: 50,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Rohit Deshmukh",
        },
      ],
      giftOccasions: ["Corporate", "Farewell", "Joining Gift"],
      recipient: ["Employee", "Executive"],
      tags: ["corporate", "office-essentials", "laptop-sleeve", "personalized"],
      ratings: { average: 4.84, count: 58 },
      bulkPricingTiers: createBulkPricing(1999),
      hoverMediaType: "image",
    },
    {
      name: "Brown Executive 7-in-1 Travel & Work Hamper",
      slug: "brown-executive-7-in-1-travel-work-hamper",
      description:
        "Luxury caramel brown corporate hamper engineered for modern executives on the move, with passport wallet, thermo flask, A5 journal, pen, keychain, and cable organizer.",
      price: 2599,
      comparePrice: 3599,
      images: [
        "/uploads/products/corporate/Brown-Executive_-7-in-1-_Custom_-Gift-_Hampers_-for-_Work-_-Travel_2.webp",
      ],
      category: catCorporate,
      stock: 175,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name for Hamper",
      personalizationZones: [
        {
          id: "zone-brown-7in1-diary",
          name: "Journal Monogram",
          x: 50,
          y: 52,
          fontSize: 16,
          textColor: "#FEF3C7",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Siddharth M.",
        },
      ],
      giftOccasions: ["Corporate", "Annual Event", "Executive Gifting"],
      recipient: ["Executive", "Client", "Director"],
      tags: ["corporate", "travel", "executive", "7-in-1", "brown-leather", "personalized"],
      ratings: { average: 4.97, count: 118 },
      bulkPricingTiers: createBulkPricing(2599),
      hoverMediaType: "image",
    },
    {
      name: "Grey Premium 7-in-1 Personalized Executive Gift Hamper",
      slug: "grey-premium-7-in-1-personalized-executive-gift-hamper",
      description:
        "Sophisticated charcoal grey 7-in-1 gift set including premium insulated flask, soft-touch diary, executive pen, card wallet, keychain, and tech desk accessories.",
      price: 2499,
      comparePrice: 3399,
      images: [
        "/uploads/products/corporate/Grey-Premium-7-in-1-Personalized-Executive-Gift-Hampers_2.webp",
      ],
      category: catCorporate,
      stock: 130,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-grey-7in1-flask",
          name: "Flask & Diary Name",
          x: 50,
          y: 48,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Amitabh Sen",
        },
      ],
      giftOccasions: ["Corporate", "Onboarding", "Client Appreciation"],
      recipient: ["Employee", "Colleague", "Manager"],
      tags: ["corporate", "grey", "7-in-1", "executive", "personalized"],
      ratings: { average: 4.9, count: 64 },
      bulkPricingTiers: createBulkPricing(2499),
      hoverMediaType: "image",
    },
    {
      name: "Personalized CXO Signature Elite Gift Set",
      slug: "personalized-cxo-signature-elite-gift-set",
      description:
        "Top-tier bespoke CXO gift box with premium leather folio organizer, luxury fountain pen, stainless steel thermos, RFID wallet, and business card case in a satin presentation box.",
      price: 3499,
      comparePrice: 4999,
      images: [
        "/uploads/products/corporate/Personalised_CXO_Signature_Elite_Gift_Set.jpg",
      ],
      category: catCorporate,
      stock: 80,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter CXO / Executive Name",
      personalizationZones: [
        {
          id: "zone-cxo-name",
          name: "Folio Cover Brass Plate",
          x: 50,
          y: 54,
          fontSize: 18,
          textColor: "#FCD34D",
          rotation: 0,
          isCurved: false,
          maxChars: 20,
          sampleText: "R. K. Singhania",
        },
      ],
      giftOccasions: ["Corporate", "Executive Gifting", "Milestone Celebration"],
      recipient: ["Executive", "CEO", "VIP Client"],
      tags: ["cxo", "elite", "luxury-corporate", "executive", "personalized"],
      ratings: { average: 5.0, count: 76 },
      bulkPricingTiers: createBulkPricing(3499),
      hoverMediaType: "image",
    },
    {
      name: "Premium 6-in-1 Personalized Backpack Gift Set with Tumbler",
      slug: "premium-6-in-1-personalized-backpack-gift-set-with-tumbler",
      description:
        "Contemporary 6-in-1 business backpack set complete with vacuum insulated coffee tumbler, engraved pen, metal keychain, and matching notebook.",
      price: 2299,
      comparePrice: 3199,
      images: [
        "/uploads/products/corporate/Premium-6-in-1-Personalized-Backpack-Gift-Set-with-Tumbler.webp",
      ],
      category: catCorporate,
      stock: 120,
      isFeatured: false,
      isBestSeller: false,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-backpack-6in1-name",
          name: "Notebook Monogram",
          x: 50,
          y: 50,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Manish Roy",
        },
      ],
      giftOccasions: ["Corporate", "Onboarding", "Youth Festival"],
      recipient: ["Employee", "Client"],
      tags: ["corporate", "backpack", "tumbler", "6-in-1", "personalized"],
      ratings: { average: 4.86, count: 51 },
      bulkPricingTiers: createBulkPricing(2299),
      hoverMediaType: "image",
    },

    // ═════════════════════════════════════════════════════════════════
    // CATEGORY: DIWALI & FESTIVE GIFTS
    // ═════════════════════════════════════════════════════════════════
    {
      name: "Shubh Deepavali Royal Celebration Hamper",
      slug: "shubh-deepavali-royal-celebration-hamper",
      description:
        "Traditional Diwali gift box featuring handcrafted terracotta diyas, premium California almonds, roasted cashews, and artisanal sweets in an ornamental box.",
      price: 1699,
      comparePrice: 2299,
      images: ["/uploads/products/diwali/1.webp"],
      category: catDiwali,
      stock: 220,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Diwali", "Festive", "New Year"],
      recipient: ["Family", "Client", "Friends"],
      tags: ["diwali", "festive", "dry-fruits", "diyas", "royal-celebration"],
      ratings: { average: 4.96, count: 164 },
      bulkPricingTiers: createBulkPricing(1699),
      hoverMediaType: "image",
    },
    {
      name: "Diwali Corporate Gift Set - Grey Laptop Bag with Planner, Bottle, Baklava & Diyas",
      slug: "diwali-corporate-grey-laptop-bag-set",
      description:
        "Premium Diwali business gift combo with executive grey laptop bag, undated diary planner, stainless bottle, authentic Turkish baklava, and brass diyas.",
      price: 2699,
      comparePrice: 3699,
      images: [
        "/uploads/products/diwali/DiwaliBusinessGifts_GreyLaptopBagSetwithPlanner_Bottle_Baklava_Diyas_grey_-Giftana.webp",
      ],
      category: catDiwali,
      stock: 150,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name / Company Name",
      personalizationZones: [
        {
          id: "zone-diwali-grey-planner",
          name: "Planner Name",
          x: 48,
          y: 46,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 18,
          sampleText: "Infosys Diwali 2026",
        },
      ],
      giftOccasions: ["Diwali", "Corporate", "Festive"],
      recipient: ["Client", "Employee", "Partner"],
      tags: ["diwali", "corporate", "laptop-bag", "baklava", "diyas", "personalized"],
      ratings: { average: 4.94, count: 112 },
      bulkPricingTiers: createBulkPricing(2699),
      hoverMediaType: "image",
    },
    {
      name: "Diwali Festive Hamper - Surya Rath Decorative Plaque with Almond Brittle & Diyas",
      slug: "diwali-surya-rath-plaque-almond-brittle-hamper",
      description:
        "Artistic Surya Rath brass-finish decorative memento paired with crunchy gourmet almond brittle and hand-painted wax diyas in a regal festive gift box.",
      price: 1899,
      comparePrice: 2599,
      images: [
        "/uploads/products/diwali/DiwaliFestiveHamper_SuryaRathDecorativePlaquewithAlmondBrittle_Diyas-Giftana.webp",
      ],
      category: catDiwali,
      stock: 140,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Diwali", "Festive", "Housewarming"],
      recipient: ["Family", "Client", "Colleague"],
      tags: ["diwali", "surya-rath", "almond-brittle", "festive-hamper"],
      ratings: { average: 4.91, count: 87 },
      bulkPricingTiers: createBulkPricing(1899),
      hoverMediaType: "image",
    },
    {
      name: "Diwali Gift Set - Laxmi Ganesh Idol with Smoor Chocolates & Shubh Aangan Kit",
      slug: "diwali-laxmi-ganesh-smoor-chocolate-gift-set",
      description:
        "Divine brass electroplated Laxmi Ganesh idols accompanied by luxury Smoor couverture chocolates, toran, pooja essentials, and brass diyas.",
      price: 2199,
      comparePrice: 2999,
      images: [
        "/uploads/products/diwali/DiwaliGiftSet_LaxmiGaneshIdolSetwithSmoorChocolate_ShubhAanganKit_Diyas-giftana.webp",
      ],
      category: catDiwali,
      stock: 190,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Diwali", "Puja", "Festive"],
      recipient: ["Family", "Client", "Parents"],
      tags: ["diwali", "laxmi-ganesh", "smoor", "pooja", "festive"],
      ratings: { average: 4.97, count: 153 },
      bulkPricingTiers: createBulkPricing(2199),
      hoverMediaType: "image",
    },
    {
      name: "Diwali Office Gifts - Laptop Bag Set with Notebook, Bottle, Baklava & Diyas (Royal Blue)",
      slug: "diwali-office-gifts-laptop-bag-set-royal-blue",
      description:
        "Regal blue business laptop bag paired with gold-embossed notebook, temperature bottle, pistachio baklava, and handcrafted festive diyas.",
      price: 2699,
      comparePrice: 3699,
      images: [
        "/uploads/products/diwali/DiwaliOfficeGifts-LaptopBagSetwithNotebook_Bottle_Baklava_Diyas_blue_-Giftana.webp",
      ],
      category: catDiwali,
      stock: 160,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-diwali-blue-notebook",
          name: "Notebook Title",
          x: 50,
          y: 45,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 18,
          sampleText: "Tata Digital",
        },
      ],
      giftOccasions: ["Diwali", "Corporate", "Annual Celebration"],
      recipient: ["Client", "Employee"],
      tags: ["diwali", "blue-bag", "corporate", "baklava", "personalized"],
      ratings: { average: 4.92, count: 83 },
      bulkPricingTiers: createBulkPricing(2699),
      hoverMediaType: "image",
    },
    {
      name: "Diwali Royal Harmony Premium Corporate Gift Hamper",
      slug: "diwali-royal-harmony-premium-corporate-hamper",
      description:
        "Grand Diwali hamper featuring gold-rimmed brass diya set, organic honey jar, silver-plated coin, luxury Medjool dates, and assorted nuts in an embroidered trunk.",
      price: 3199,
      comparePrice: 4299,
      images: [
        "/uploads/products/diwali/DiwaliRoyalHarmony-PremiumCorporateGiftHamper-giftana.webp",
      ],
      category: catDiwali,
      stock: 110,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Diwali", "VIP Gifting", "Festive"],
      recipient: ["VIP Client", "Executive", "Family"],
      tags: ["diwali", "royal-harmony", "luxury-trunk", "festive", "dry-fruits"],
      ratings: { average: 4.99, count: 129 },
      bulkPricingTiers: createBulkPricing(3199),
      hoverMediaType: "image",
    },
    {
      name: "Shubh Aangan Festive Corporate Hamper with Wireless Speaker & Almond Treats",
      slug: "shubh-aangan-festive-hamper-wireless-speaker",
      description:
        "Tech-meets-tradition Diwali hamper with high-bass wooden wireless Bluetooth speaker, crunchy almond cookies, dark chocolate brittle, and scented diyas.",
      price: 2499,
      comparePrice: 3499,
      images: [
        "/uploads/products/diwali/FestiveCorporateGifts_ShubhAanganHamperwithWirelessSpeaker_AlmondCookies_Brittle-Giftana.webp",
      ],
      category: catDiwali,
      stock: 135,
      isFeatured: true,
      isBestSeller: false,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-diwali-speaker-name",
          name: "Speaker Grille Monogram",
          x: 52,
          y: 50,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Harish Patel",
        },
      ],
      giftOccasions: ["Diwali", "Festive", "Annual Event"],
      recipient: ["Employee", "Client", "Friends"],
      tags: ["diwali", "bluetooth-speaker", "shubh-aangan", "cookies", "personalized"],
      ratings: { average: 4.88, count: 67 },
      bulkPricingTiers: createBulkPricing(2499),
      hoverMediaType: "image",
    },
    {
      name: "Grand Laxmi Ganesh Charan Hamper with Dry Fruits, Ferrero Rocher & Diyas",
      slug: "grand-laxmi-ganesh-charan-hamper-dry-fruits",
      description:
        "Auspicious Charan paduka Laxmi Ganesh gift ensemble with 4-jar dry fruit assortment (Cashews, Almonds, Pistachios, Raisins), Ferrero Rocher, and glowing diyas.",
      price: 2299,
      comparePrice: 3199,
      images: [
        "/uploads/products/diwali/PremiumDiwaliGifts_GrandLaxmiGaneshCharanHamperwithDryFruits_Ferrero_Diyas-Giftana.webp",
      ],
      category: catDiwali,
      stock: 170,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: false,
      giftOccasions: ["Diwali", "Puja", "Family Gathering"],
      recipient: ["Family", "Relatives", "Client"],
      tags: ["diwali", "laxmi-charan", "ferrero-rocher", "dry-fruits", "puja-kit"],
      ratings: { average: 4.95, count: 141 },
      bulkPricingTiers: createBulkPricing(2299),
      hoverMediaType: "image",
    },

    // ═════════════════════════════════════════════════════════════════
    // CATEGORY: PERSONALIZED GIFTS
    // ═════════════════════════════════════════════════════════════════
    {
      name: "Elegant Name-Engraved Ladies Wallet for Everyday Style",
      slug: "elegant-name-engraved-ladies-wallet",
      description:
        "Stylish slim bi-fold ladies wallet with dedicated card slots, phone pouch, and high-precision laser engraved name personalization.",
      price: 749,
      comparePrice: 1099,
      images: [
        "/uploads/products/personalised/Elegant-Name-Engraved-Ladies-Wallet-for-Everyday-Style.gif",
      ],
      category: catPersonalized,
      stock: 190,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name for Wallet",
      personalizationZones: [
        {
          id: "zone-ladies-wallet",
          name: "Wallet Front Monogram",
          x: 50,
          y: 65,
          fontSize: 16,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 14,
          sampleText: "Deepika P.",
        },
      ],
      giftOccasions: ["Birthday", "Anniversary", "Casual", "Women's Day"],
      recipient: ["Her", "Wife", "Sister", "Friend"],
      tags: ["wallet", "for-her", "personalized", "engraved", "gif-preview"],
      ratings: { average: 4.92, count: 98 },
      bulkPricingTiers: createBulkPricing(749),
      hoverMediaType: "image",
    },
    {
      name: "Fancy Stainless Steel Coffee Mug with LED Temperature Display",
      slug: "stainless-steel-coffee-mug-led-temperature-display",
      description:
        "Double-walled 450ml travel mug with touch-activated smart LED temperature readout and spill-proof flip lid. Laser-engraved with your custom name or initials.",
      price: 699,
      comparePrice: 999,
      images: [
        "/uploads/products/personalised/Fancy-Stainless-Steel-Coffee-Mug-with-LED-Temperature-Display.webp",
      ],
      category: catPersonalized,
      stock: 210,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-led-mug",
          name: "Mug Body Engraving",
          x: 50,
          y: 55,
          fontSize: 16,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Aman Gupta",
        },
      ],
      giftOccasions: ["Daily Use", "Birthday", "Corporate", "Gym"],
      recipient: ["Him", "Her", "Colleague", "Friend"],
      tags: ["temperature-mug", "coffee-mug", "personalized", "travel-mug", "led-display"],
      ratings: { average: 4.9, count: 135 },
      bulkPricingTiers: createBulkPricing(699),
      hoverMediaType: "image",
    },
    {
      name: "Personalized Velvet Jewellery Organiser - Forest Green",
      slug: "personalized-velvet-jewellery-organiser-forest-green",
      description:
        "Compact multi-compartment travel jewellery storage case with soft anti-scratch lining and custom name calligraphy in gold lettering.",
      price: 799,
      comparePrice: 1199,
      images: ["/uploads/products/personalised/Jewellery_Storage_Box-green.jpg"],
      category: catPersonalized,
      stock: 140,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name for Organiser",
      personalizationZones: [
        {
          id: "zone-velvet-box-pers",
          name: "Lid Gold Calligraphy",
          x: 50,
          y: 52,
          fontSize: 18,
          textColor: "#FCD34D",
          rotation: 0,
          isCurved: false,
          maxChars: 14,
          sampleText: "Shraddha",
        },
      ],
      giftOccasions: ["Birthday", "Wedding", "Bridal Shower", "Anniversary"],
      recipient: ["Her", "Bride", "Wife", "Sister"],
      tags: ["jewellery-box", "personalized", "for-her", "velvet", "forest-green"],
      ratings: { average: 4.89, count: 74 },
      bulkPricingTiers: createBulkPricing(799),
      hoverMediaType: "image",
    },
    {
      name: "King Charm Personalized Executive Diary Organizer",
      slug: "king-charm-personalized-executive-diary",
      description:
        "Premium textured leatherette A5 notebook with metallic King Crown charm and custom laser-cut metallic nameplate.",
      price: 599,
      comparePrice: 899,
      images: ["/uploads/products/personalised/King-charm-Zebra-diary_2.webp"],
      category: catPersonalized,
      stock: 180,
      isFeatured: false,
      isBestSeller: false,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-king-diary",
          name: "Brass Nameplate",
          x: 50,
          y: 65,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "King Rajesh",
        },
      ],
      giftOccasions: ["Birthday", "Corporate", "Farewell", "Student"],
      recipient: ["Him", "Husband", "Brother", "Colleague"],
      tags: ["diary", "king-charm", "notebook", "personalized", "zebra-texture"],
      ratings: { average: 4.82, count: 61 },
      bulkPricingTiers: createBulkPricing(599),
      hoverMediaType: "image",
    },
    {
      name: "Personalized Tan Leather Planner Diary",
      slug: "personalized-tan-leather-planner-diary",
      description:
        "Minimalist vintage tan faux leather refillable diary with pen loop, magnetic strap closure, and custom embossed name.",
      price: 649,
      comparePrice: 949,
      images: ["/uploads/products/personalised/Personalized_Tan_Planner_Diary.webp"],
      category: catPersonalized,
      stock: 165,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name for Diary",
      personalizationZones: [
        {
          id: "zone-tan-diary",
          name: "Strap / Cover Name",
          x: 48,
          y: 52,
          fontSize: 15,
          textColor: "#3E2723",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Dr. Alok Verma",
        },
      ],
      giftOccasions: ["Corporate", "Birthday", "Daily Planning", "Doctors Day"],
      recipient: ["Colleague", "Student", "Executive", "Doctor"],
      tags: ["planner", "tan-diary", "personalized", "stationery", "leatherette"],
      ratings: { average: 4.87, count: 58 },
      bulkPricingTiers: createBulkPricing(649),
      hoverMediaType: "image",
    },
    {
      name: "Personalized Travel Utility Pouch with Name Charm",
      slug: "personalized-travel-utility-pouch-with-name-charm",
      description:
        "Multipurpose zip pouch for toiletries, shaving gear, or makeup essentials with personalized metal charm and engraved name strip.",
      price: 499,
      comparePrice: 799,
      images: [
        "/uploads/products/personalised/Personalized_Travel_Pouch_with_Name_Charm-1.webp",
      ],
      category: catPersonalized,
      stock: 200,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name for Pouch",
      personalizationZones: [
        {
          id: "zone-pouch-name",
          name: "Leather Name Tag",
          x: 50,
          y: 60,
          fontSize: 14,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 14,
          sampleText: "Priya Malik",
        },
      ],
      giftOccasions: ["Travel", "Birthday", "Gifting", "Summer Trip"],
      recipient: ["Him", "Her", "Traveler", "Colleague"],
      tags: ["travel-pouch", "personalized", "toiletry-kit", "charm"],
      ratings: { average: 4.85, count: 79 },
      bulkPricingTiers: createBulkPricing(499),
      hoverMediaType: "image",
    },
    {
      name: "Personalized Ceramic Coffee Mug - Pristine White",
      slug: "personalized-ceramic-coffee-mug-pristine-white",
      description:
        "High-grade ceramic white coffee mug (330ml) microwave & dishwasher safe, personalized with your custom message or typography.",
      price: 399,
      comparePrice: 599,
      images: ["/uploads/products/personalised/Personalized-Coffee-Mug-white.webp"],
      category: catPersonalized,
      stock: 250,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name or Quote",
      personalizationZones: [
        {
          id: "zone-mug-name",
          name: "Mug Center Typography",
          x: 50,
          y: 50,
          fontSize: 16,
          textColor: "#18181B",
          rotation: 0,
          isCurved: false,
          maxChars: 18,
          sampleText: "Best Boss Ever",
        },
      ],
      giftOccasions: ["Birthday", "Friendship Day", "Office", "Secret Santa"],
      recipient: ["Friend", "Colleague", "Family", "Teacher"],
      tags: ["mug", "ceramic-mug", "personalized", "white-mug", "daily-use"],
      ratings: { average: 4.93, count: 189 },
      bulkPricingTiers: createBulkPricing(399),
      hoverMediaType: "image",
    },
    {
      name: "Premium Personalized 3-in-1 Wooden Utility Gift Set",
      slug: "premium-personalized-3-in-1-wooden-utility-gift-set",
      description:
        "Handcrafted natural birch wood desk organizer combo with mobile stand, visiting card holder, and wooden pen engraved with your name.",
      price: 1199,
      comparePrice: 1699,
      images: [
        "/uploads/products/personalised/Premium-Personalised-3-in-1-Wooden-Utility-Gift-Set_1.webp",
      ],
      category: catPersonalized,
      stock: 115,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-wooden-stand-name",
          name: "Mobile Stand Base",
          x: 50,
          y: 60,
          fontSize: 15,
          textColor: "#3E2723",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Er. Sandeep Rao",
        },
      ],
      giftOccasions: ["Corporate", "Farewell", "Father's Day", "Work Anniversary"],
      recipient: ["Him", "Boss", "Father", "Executive"],
      tags: ["wooden-set", "desk-organizer", "personalized", "eco-friendly", "3-in-1"],
      ratings: { average: 4.95, count: 108 },
      bulkPricingTiers: createBulkPricing(1199),
      hoverMediaType: "image",
    },

    // ═════════════════════════════════════════════════════════════════
    // CATEGORY: PERSONALIZED HAMPERS (Gift Hampers / Eco-Friendly)
    // ═════════════════════════════════════════════════════════════════
    {
      name: "5-in-1 Matte Rubber Finish Executive Hamper - Royal Blue",
      slug: "5-in-1-matte-rubber-finish-executive-hamper-royal-blue",
      description:
        "Soft-touch matte blue 5-in-1 set including rubber-coated vacuum bottle, temperature tumbler, undated diary, metallic pen, and keychain.",
      price: 1899,
      comparePrice: 2699,
      images: [
        "/uploads/products/personalised-hampers/5-in-1-rubber-bottle-diary-pen-keychain-tumbler-blue.webp",
      ],
      category: catHampers,
      stock: 140,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-blue-5in1-diary",
          name: "Diary & Bottle Name",
          x: 50,
          y: 48,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Aditya Roy",
        },
      ],
      giftOccasions: ["Corporate", "Birthday", "Welcome Kit", "Milestone"],
      recipient: ["Him", "Colleague", "Client", "Friend"],
      tags: ["hamper", "5-in-1", "matte-blue", "rubber-finish", "personalized"],
      ratings: { average: 4.94, count: 96 },
      bulkPricingTiers: createBulkPricing(1899),
      hoverMediaType: "image",
    },
    {
      name: "All-in-One Executive Desk Set with Clock, Pendrive & Rope Bottle",
      slug: "all-in-one-executive-desk-set-clock-pendrive",
      description:
        "Comprehensive desk accessory kit with integrated digital desk clock, 32GB USB pendrive, rope handle stainless bottle, metal phone stand, cardholder, diary & pen.",
      price: 2799,
      comparePrice: 3899,
      images: [
        "/uploads/products/personalised-hampers/diary-keychain-pendrive-stand-rope-bottle-cardholder-desk-clock.webp",
      ],
      category: catHampers,
      stock: 110,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-clock-desk-name",
          name: "Diary Title",
          x: 52,
          y: 44,
          fontSize: 16,
          textColor: "#FCD34D",
          rotation: 0,
          isCurved: false,
          maxChars: 18,
          sampleText: "Sunil Mittal",
        },
      ],
      giftOccasions: ["Milestone", "Corporate", "Annual Day", "Retirement"],
      recipient: ["Executive", "Client", "Employee", "Mentor"],
      tags: ["desk-clock", "pendrive", "hamper", "all-in-one", "personalized", "executive"],
      ratings: { average: 4.98, count: 122 },
      bulkPricingTiers: createBulkPricing(2799),
      hoverMediaType: "image",
    },
    {
      name: "Elite 5-in-1 Custom Engraved Office Gift Hamper - Matte Black",
      slug: "elite-5-in-1-custom-engraved-office-hamper-matte-black",
      description:
        "Stealth matte black 5-in-1 corporate suite with laser-engraved thermos flask, A5 journal with metal lock, rollerball pen, keychain, and cardholder.",
      price: 1899,
      comparePrice: 2599,
      images: [
        "/uploads/products/personalised-hampers/Elite-5-in-1-Custom-Engraved-Office-Gift-Hamper_Black.webp",
      ],
      category: catHampers,
      stock: 160,
      isFeatured: false,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-black-5in1-name",
          name: "Thermos & Journal Engraving",
          x: 50,
          y: 50,
          fontSize: 15,
          textColor: "#FFFFFF",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Akshay K.",
        },
      ],
      giftOccasions: ["Corporate", "Birthday", "Executive", "Farewell"],
      recipient: ["Him", "Colleague", "Manager", "Brother"],
      tags: ["matte-black", "5-in-1", "elite-hamper", "personalized"],
      ratings: { average: 4.91, count: 85 },
      bulkPricingTiers: createBulkPricing(1899),
      hoverMediaType: "image",
    },
    {
      name: "Green Luxe 7-in-1 Bamboo Eco Executive Gift Hamper",
      slug: "green-luxe-7-in-1-bamboo-eco-executive-gift-hamper",
      description:
        "Sustainable luxury bamboo executive combo featuring organic bamboo insulated bottle, wooden ballpoint pen, bamboo diary, keychain, phone stand, and mug.",
      price: 2399,
      comparePrice: 3299,
      images: [
        "/uploads/products/personalised-hampers/Green-Luxe-7-in-1-Bamboo-Executive-Gift-Hamper_2.jpg",
      ],
      category: catEco,
      stock: 125,
      isFeatured: true,
      isBestSeller: true,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-bamboo-7in1-name",
          name: "Bamboo Flask Engraving",
          x: 50,
          y: 50,
          fontSize: 16,
          textColor: "#3E2723",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Eco Warrior Nidhi",
        },
      ],
      giftOccasions: ["Corporate", "Earth Day", "Festive", "Annual Event"],
      recipient: ["Employee", "Client", "Partner", "Eco Enthusiast"],
      tags: ["bamboo", "eco-friendly", "7-in-1", "hamper", "green-luxe", "personalized"],
      ratings: { average: 4.97, count: 114 },
      bulkPricingTiers: createBulkPricing(2399),
      hoverMediaType: "image",
    },
    {
      name: "5-in-1 Eco Cork Diary, Bamboo Bottle & Keychain Gift Set",
      slug: "5-in-1-eco-cork-diary-bamboo-bottle-keychain-set",
      description:
        "Biodegradable natural cork and bamboo 5-in-1 gift set including cork texture notebook, bamboo bottle with tea infuser, bamboo pen, and cardholder.",
      price: 1999,
      comparePrice: 2799,
      images: [
        "/uploads/products/personalised-hampers/Personalized5in1CorkDiary_Pen_Keychain_CardHolder_BambooBottle.webp",
      ],
      category: catEco,
      stock: 140,
      isFeatured: true,
      isBestSeller: false,
      isPersonalizable: true,
      personalizationPrompt: "Enter Name to Engrave",
      personalizationZones: [
        {
          id: "zone-cork-5in1-name",
          name: "Cork Cover Name",
          x: 50,
          y: 48,
          fontSize: 15,
          textColor: "#4E342E",
          rotation: 0,
          isCurved: false,
          maxChars: 16,
          sampleText: "Pooja Hegde",
        },
      ],
      giftOccasions: ["Corporate", "Welcome Kit", "Eco Friendly", "Conference"],
      recipient: ["Colleague", "Client", "Employee"],
      tags: ["cork-diary", "bamboo-bottle", "eco-hamper", "5-in-1", "personalized"],
      ratings: { average: 4.89, count: 68 },
      bulkPricingTiers: createBulkPricing(1999),
      hoverMediaType: "image",
    },
  ]

  const inserted = await Product.insertMany(newProducts)
  console.log(`✅ Successfully seeded ${inserted.length} real products from 'PS gift'!`)

  process.exit(0)
}

seedPsGift().catch((err) => {
  console.error("❌ Error seeding PS gift products:", err)
  process.exit(1)
})
